// src/lib/mouseDatabase.ts
// Central mouse database with specs + affiliate links

export interface MouseSpec {
    id: string;
    name: string;
    brand: string;
    weight: number; // grams
    shape: 'Symmetrical' | 'Ergonomic Right' | 'Ergonomic Left';
    connectivity: 'Wired' | 'Wireless' | 'Both';
    sensor: string;
    maxDpi: number;
    pollingRate: string; // e.g., "1000Hz" or "4000Hz / 8000Hz"
    clicks: string; // switch type
    length: number; // mm
    width: number; // mm
    height: number; // mm
    price: string; // USD approximate
    affiliateLink: string;
    badge?: string;
    proUsage: string[]; // pro players known to use it
    games: string[]; // recommended for
    proScore: number; // 1-10, how popular among pros
    rating: number; // overall rating out of 5
    category: 'Ultra-Light' | 'Competitive' | 'Ergonomic' | 'Value';
}

export const mouseDatabase: MouseSpec[] = [
    {
        id: 'gprox-superlight2',
        name: 'G Pro X Superlight 2',
        brand: 'Logitech',
        weight: 60,
        shape: 'Symmetrical',
        connectivity: 'Wireless',
        sensor: 'HERO 2',
        maxDpi: 32000,
        pollingRate: '1000Hz',
        clicks: 'Mechanical (Optical-mechanical hybrid)',
        length: 125,
        width: 63.5,
        height: 40,
        price: '$159',
        affiliateLink: 'https://amzn.to/3PEwF13',
        badge: '🏆 #1 Pro Choice',
        proUsage: ['TenZ', 'ScreaM', 'ShadoW', 'Navi s1mple'],
        games: ['Valorant', 'CS2'],
        proScore: 10,
        rating: 4.9,
        category: 'Ultra-Light',
    },
    {
        id: 'viper-v3-pro',
        name: 'Viper V3 Pro',
        brand: 'Razer',
        weight: 54,
        shape: 'Symmetrical',
        connectivity: 'Wireless',
        sensor: 'Focus Pro 35K',
        maxDpi: 35000,
        pollingRate: '4000Hz / 8000Hz',
        clicks: 'Optical (zero debounce)',
        length: 127.4,
        width: 57.6,
        height: 37.8,
        price: '$149',
        affiliateLink: 'https://amzn.to/3RQtILr',
        badge: '⚡ Lightest Wireless',
        proUsage: ['jawgemo', 'Aspas', 'Derke'],
        games: ['Valorant', 'CS2', 'Apex'],
        proScore: 9,
        rating: 4.8,
        category: 'Ultra-Light',
    },
    {
        id: 'deathadder-v3-pro',
        name: 'DeathAdder V3 Pro',
        brand: 'Razer',
        weight: 63,
        shape: 'Ergonomic Right',
        connectivity: 'Wireless',
        sensor: 'Focus Pro 30K',
        maxDpi: 30000,
        pollingRate: '4000Hz / 8000Hz',
        clicks: 'Optical (zero debounce)',
        length: 128,
        width: 68,
        height: 44,
        price: '$149',
        affiliateLink: 'https://amzn.to/4agdh1h',
        badge: '👑 Best Ergonomic',
        proUsage: ['tarik', 'Demon1', 'yay'],
        games: ['Valorant', 'CS2'],
        proScore: 8,
        rating: 4.7,
        category: 'Ergonomic',
    },
    {
        id: 'lamzu-atlantis-v2',
        name: 'Atlantis OG V2',
        brand: 'Lamzu',
        weight: 55,
        shape: 'Symmetrical',
        connectivity: 'Wireless',
        sensor: 'PixArt PAW3395',
        maxDpi: 26000,
        pollingRate: '4000Hz',
        clicks: 'Kailh GM 8.0',
        length: 122,
        width: 60,
        height: 37,
        price: '$89',
        affiliateLink: 'https://amzn.to/4uA6Lut',
        badge: '🎯 Boutique Elite',
        proUsage: ['Less', 'FNS'],
        games: ['Valorant', 'CS2'],
        proScore: 7,
        rating: 4.8,
        category: 'Ultra-Light',
    },
    {
        id: 'pulsar-x2v2',
        name: 'X2V2 Mini',
        brand: 'Pulsar',
        weight: 52,
        shape: 'Symmetrical',
        connectivity: 'Wireless',
        sensor: 'PixArt PAW3395',
        maxDpi: 26000,
        pollingRate: '1000Hz',
        clicks: 'Kailh GM 2.0',
        length: 116,
        width: 58.5,
        height: 37.5,
        price: '$79',
        affiliateLink: 'https://amzn.to/3PEwF13',
        badge: '💰 Best Value',
        proUsage: ['Clix', 'mongraal'],
        games: ['Fortnite', 'Valorant', 'Apex'],
        proScore: 6,
        rating: 4.6,
        category: 'Value',
    },
    {
        id: 'endgame-gear-op1we',
        name: 'OP1we',
        brand: 'Endgame Gear',
        weight: 68,
        shape: 'Ergonomic Right',
        connectivity: 'Wireless',
        sensor: 'PixArt PAW3395',
        maxDpi: 26000,
        pollingRate: '1000Hz',
        clicks: 'Kailh GM 4.0',
        length: 126,
        width: 66,
        height: 43,
        price: '$99',
        affiliateLink: 'https://amzn.to/4agdh1h',
        proUsage: ['rain', 'NiKo'],
        games: ['CS2', 'Valorant'],
        proScore: 7,
        rating: 4.7,
        category: 'Ergonomic',
    },
    {
        id: 'zowie-ec2-c',
        name: 'EC2-C',
        brand: 'Zowie (BenQ)',
        weight: 73,
        shape: 'Ergonomic Right',
        connectivity: 'Wired',
        sensor: '3610',
        maxDpi: 3200,
        pollingRate: '1000Hz',
        clicks: 'Huano switches',
        length: 120,
        width: 62,
        height: 40,
        price: '$79',
        affiliateLink: 'https://amzn.to/3PEwF13',
        badge: '🔌 CS2 Classic',
        proUsage: ['ZywOo', 'device'],
        games: ['CS2'],
        proScore: 8,
        rating: 4.5,
        category: 'Competitive',
    },
    {
        id: 'gprox-wired',
        name: 'G Pro X Wired',
        brand: 'Logitech',
        weight: 61,
        shape: 'Symmetrical',
        connectivity: 'Wired',
        sensor: 'HERO 25K',
        maxDpi: 25600,
        pollingRate: '1000Hz',
        clicks: 'OMRON D2F-01F',
        length: 125,
        width: 63.5,
        height: 40,
        price: '$59',
        affiliateLink: 'https://amzn.to/3PEwF13',
        badge: '💡 Budget Pro Pick',
        proUsage: ['Many CS2 pros'],
        games: ['CS2', 'Valorant'],
        proScore: 7,
        rating: 4.6,
        category: 'Value',
    },
];
