// src/lib/pros.ts
// Comprehensive pro player database with full settings and gear

export interface ProPlayer {
    slug: string;
    name: string;
    realName: string;
    game: string;
    gameId: string;
    team: string;
    country: string;
    countryFlag: string;
    dpi: number;
    sens: number;
    cm360: number; // pre-calculated
    edpi: number;  // dpi * sens
    mouse: string;
    mouseSlug: string;
    keyboard: string;
    headset: string;
    monitor: string;
    monitorHz: number;
    mousepad: string;
    crosshairCode?: string; // Valorant crosshair code
    role: string;
    active: boolean;
    achievements: string[];
    social: { twitter?: string; twitch?: string; youtube?: string };
    bio: string;
    pollingRate: number;
    windowsSens: number;
    rawInput: boolean;
    zoomSens?: number;
}

// cm/360 formula: (360 / (sens * yaw * dpi)) * 2.54
// Valorant yaw: 0.07, CS2 yaw: 0.022, Apex yaw: 0.022, OW2 yaw: 0.006326531

function cm360Valorant(dpi: number, sens: number): number {
    return parseFloat(((360 / (sens * 0.07 * dpi)) * 2.54).toFixed(2));
}
function cm360CS2(dpi: number, sens: number): number {
    return parseFloat(((360 / (sens * 0.022 * dpi)) * 2.54).toFixed(2));
}
function cm360Apex(dpi: number, sens: number): number {
    return parseFloat(((360 / (sens * 0.022 * dpi)) * 2.54).toFixed(2));
}
function cm360OW2(dpi: number, sens: number): number {
    return parseFloat(((360 / (sens * 0.006326531 * dpi)) * 2.54).toFixed(2));
}

export const pros: ProPlayer[] = [
    // ─── VALORANT ───────────────────────────────────────────────────────────
    {
        slug: 'tenz',
        name: 'TenZ',
        realName: 'Tyson Ngo',
        game: 'Valorant',
        gameId: 'valorant',
        team: 'Sentinels',
        country: 'Canada',
        countryFlag: '🇨🇦',
        dpi: 800,
        sens: 0.3,
        cm360: cm360Valorant(800, 0.3),
        edpi: 240,
        mouse: 'Lamzu Atlantis',
        mouseSlug: 'lamzu-atlantis',
        keyboard: 'Razer BlackWidow V4 Pro',
        headset: 'Razer BlackShark V2 Pro',
        monitor: 'ASUS ROG Swift PG259QN',
        monitorHz: 360,
        mousepad: 'Artisan Zero FX M',
        crosshairCode: '0;s;1;P;o;1;0l;4;0o;2;0a;1;0f;0;1b;0',
        role: 'Duelist',
        active: true,
        achievements: ['VCT Champion 2021', '100T NA Top Performer'],
        social: { twitter: 'tenzofficial', twitch: 'tenz' },
        bio: 'TenZ is widely considered one of the best Valorant players in the world. Known for his aggressive dueling style and mechanical excellence, he helped put Sentinels on the map as a dominant force in VCT.',
        pollingRate: 1000,
        windowsSens: 6,
        rawInput: true,
    },
    {
        slug: 'aspas',
        name: 'Aspas',
        realName: 'Erick Santos',
        game: 'Valorant',
        gameId: 'valorant',
        team: 'Leviatán',
        country: 'Brazil',
        countryFlag: '🇧🇷',
        dpi: 800,
        sens: 0.4,
        cm360: cm360Valorant(800, 0.4),
        edpi: 320,
        mouse: 'Logitech G Pro X Superlight 2',
        mouseSlug: 'logitech-g-pro-x-superlight-2',
        keyboard: 'Logitech G PRO X',
        headset: 'Logitech G PRO X 2',
        monitor: 'ASUS ROG Swift PG259QN',
        monitorHz: 360,
        mousepad: 'Logitech G640',
        crosshairCode: '0;s;1;P;c;1;h;0;0l;4;0o;1;0a;1;0f;0;1b;0',
        role: 'Duelist',
        active: true,
        achievements: ['VCT Americas 2023 Winner', 'VCT Masters Champion'],
        social: { twitter: 'aspaszin', twitch: 'aspas' },
        bio: 'Aspas is the Brazilian superstar of Valorant. His raw aim and unpredictable aggression make him one of the most feared duelists in the world. He is a VCT Americas champion with Leviatán.',
        pollingRate: 1000,
        windowsSens: 6,
        rawInput: true,
    },
    {
        slug: 'demon1',
        name: 'Demon1',
        realName: 'Max Mazanov',
        game: 'Valorant',
        gameId: 'valorant',
        team: 'NRG',
        country: 'Ukraine',
        countryFlag: '🇺🇦',
        dpi: 1600,
        sens: 0.1,
        cm360: cm360Valorant(1600, 0.1),
        edpi: 160,
        mouse: 'G-Wolves HTS+ 4K',
        mouseSlug: 'g-wolves-hts-4k',
        keyboard: 'Wooting 60HE',
        headset: 'Sennheiser HD 599',
        monitor: 'ASUS ROG Swift 360Hz',
        monitorHz: 360,
        mousepad: 'Artisan FX Hien M',
        crosshairCode: '0;s;1;P;c;5;h;0;0l;4;0o;1;0a;1;0f;0;1b;0',
        role: 'Duelist',
        active: true,
        achievements: ['VCT LOCK//IN 2023', 'NRG Americas Top Fragger'],
        social: { twitter: 'demon1gg', twitch: 'demon1' },
        bio: 'Demon1 is known for his ultra-low eDPI (160) paired with exceptional raw aim. His insane 4000Hz polling rate mouse combined with the Wooting keyboard sets him apart mechanically from every other pro.',
        pollingRate: 4000,
        windowsSens: 6,
        rawInput: true,
    },
    {
        slug: 'boaster',
        name: 'Boaster',
        realName: 'Jake Howlett',
        game: 'Valorant',
        gameId: 'valorant',
        team: 'Fnatic',
        country: 'United Kingdom',
        countryFlag: '🇬🇧',
        dpi: 800,
        sens: 0.25,
        cm360: cm360Valorant(800, 0.25),
        edpi: 200,
        mouse: 'Logitech G Pro X Superlight',
        mouseSlug: 'logitech-g-pro-x-superlight',
        keyboard: 'Logitech G PRO X',
        headset: 'Razer BlackShark V2 Pro',
        monitor: 'BenQ ZOWIE XL2546K',
        monitorHz: 240,
        mousepad: 'Fnatic DASH L',
        crosshairCode: '0;p;0;c;1;s;1;0l;4;0o;2;0a;1;0f;0;1b;0',
        role: 'IGL / Controller',
        active: true,
        achievements: ['VCT EMEA Champion 2023', 'Fnatic IGL'],
        social: { twitter: 'Boaster', twitch: 'boaster' },
        bio: 'Boaster is the charismatic IGL of Fnatic and one of the most recognizable personalities in Valorant. His low sensitivity reflects his precise, controlled playstyle as an in-game leader.',
        pollingRate: 1000,
        windowsSens: 6,
        rawInput: true,
    },
    {
        slug: 'chronicle',
        name: 'Chronicle',
        realName: 'Timofey Khromov',
        game: 'Valorant',
        gameId: 'valorant',
        team: 'Fnatic',
        country: 'Russia',
        countryFlag: '🇷🇺',
        dpi: 400,
        sens: 0.65,
        cm360: cm360Valorant(400, 0.65),
        edpi: 260,
        mouse: 'Logitech G Pro X Superlight 2',
        mouseSlug: 'logitech-g-pro-x-superlight-2',
        keyboard: 'Logitech G PRO X',
        headset: 'Logitech G PRO X 2',
        monitor: 'BenQ ZOWIE XL2546K',
        monitorHz: 240,
        mousepad: 'Logitech G640',
        role: 'Sentinel',
        active: true,
        achievements: ['VCT 2022 Champion', 'VCT Masters Finalist'],
        social: { twitter: 'chroniclegg' },
        bio: 'Chronicle is a former CS:GO professional who transitioned to Valorant and became one of the best sentinel players in EMEA. His CS:GO background gives him an exceptional game sense.',
        pollingRate: 1000,
        windowsSens: 6,
        rawInput: true,
    },
    {
        slug: 'yay',
        name: 'yay',
        realName: 'Jaccob Whiteford',
        game: 'Valorant',
        gameId: 'valorant',
        team: 'G2 Esports',
        country: 'United States',
        countryFlag: '🇺🇸',
        dpi: 800,
        sens: 0.279,
        cm360: cm360Valorant(800, 0.279),
        edpi: 223,
        mouse: 'Logitech G Pro X Superlight 2',
        mouseSlug: 'logitech-g-pro-x-superlight-2',
        keyboard: 'Logitech G PRO X Keyboard',
        headset: 'Logitech G PRO X 2',
        monitor: 'Alienware AW2521H',
        monitorHz: 360,
        mousepad: 'Logitech G640',
        crosshairCode: '0;s;1;P;c;5;o;0.449;0l;4;0o;1;0a;1;0f;0;1b;0',
        role: 'Operator / Duelist',
        active: true,
        achievements: ['VCT Masters Berlin 2021', 'Dubbed "The Operator"'],
        social: { twitter: 'yay', twitch: 'yay' },
        bio: 'yay is one of the greatest Valorant players ever, nicknamed "The Operator" for his terrifying one-tap ability. His career-best performance at VCT Masters Berlin cemented his legacy.',
        pollingRate: 1000,
        windowsSens: 6,
        rawInput: true,
    },
    {
        slug: 'nats',
        name: 'nAts',
        realName: 'Ayaz Akhmetshin',
        game: 'Valorant',
        gameId: 'valorant',
        team: 'Team Spirit',
        country: 'Russia',
        countryFlag: '🇷🇺',
        dpi: 400,
        sens: 0.86,
        cm360: cm360Valorant(400, 0.86),
        edpi: 344,
        mouse: 'Logitech G Pro X Superlight 2',
        mouseSlug: 'logitech-g-pro-x-superlight-2',
        keyboard: 'Logitech G PRO X',
        headset: 'Logitech G PRO X 2',
        monitor: 'BenQ ZOWIE XL2546K',
        monitorHz: 240,
        mousepad: 'Logitech G840',
        role: 'Sentinel',
        active: true,
        achievements: ['VCT Champion 2022', 'Best Cypher Player World'],
        social: { twitter: 'nAtsCS' },
        bio: 'nAts is the Cypher specialist who helped Gambit (now Team Spirit) dominate global Valorant. His game sense and trapping setups are legendary among Valorant analysts.',
        pollingRate: 1000,
        windowsSens: 6,
        rawInput: true,
    },

    // ─── CS2 ──────────────────────────────────────────────────────────────────
    {
        slug: 's1mple',
        name: 's1mple',
        realName: 'Oleksandr Kostyliev',
        game: 'CS2',
        gameId: 'csgo',
        team: 'Team Falcons',
        country: 'Ukraine',
        countryFlag: '🇺🇦',
        dpi: 400,
        sens: 3.09,
        cm360: cm360CS2(400, 3.09),
        edpi: 1236,
        mouse: 'Logitech G Pro X Superlight 2',
        mouseSlug: 'logitech-g-pro-x-superlight-2',
        keyboard: 'HyperX Alloy FPS Pro',
        headset: 'HyperX Cloud Alpha',
        monitor: 'BenQ ZOWIE XL2546K',
        monitorHz: 240,
        mousepad: 'Logitech G840',
        role: 'AWPer',
        active: true,
        achievements: ['HLTV #1 Player 2018-2022', 'PGL Major Stockholm Winner', 'IEM Katowice 2022'],
        social: { twitter: 's1mpleO', twitch: 's1mple' },
        bio: 's1mple is widely regarded as the greatest CS:GO/CS2 player of all time. Named HLTV #1 player 5 times, his AWP skills and raw fragging power have never been matched. He uses a relatively high sensitivity for a pro AWPer.',
        pollingRate: 1000,
        windowsSens: 6,
        rawInput: true,
    },
    {
        slug: 'niko',
        name: 'NiKo',
        realName: 'Nikola Kovač',
        game: 'CS2',
        gameId: 'csgo',
        team: 'G2 Esports',
        country: 'Bosnia',
        countryFlag: '🇧🇦',
        dpi: 400,
        sens: 1.4,
        cm360: cm360CS2(400, 1.4),
        edpi: 560,
        mouse: 'Zowie EC2-GW',
        mouseSlug: 'zowie-ec2-gw',
        keyboard: 'Ducky One 2 Mini',
        headset: 'HyperX Cloud II',
        monitor: 'BenQ ZOWIE XL2546K',
        monitorHz: 240,
        mousepad: 'Zowie G-SR',
        role: 'Rifler / Entry',
        active: true,
        achievements: ['HLTV #2 Player 2022', 'IEM Cologne 2023 Winner', 'G2 Captain'],
        social: { twitter: 'G2NiKo', twitch: 'niko' },
        bio: 'NiKo is one of the best riflers in CS history. His precise 1.4 sensitivity at 400 DPI gives him exceptional crosshair placement and allows for both micro-adjustments and wide swings with equal efficiency.',
        pollingRate: 1000,
        windowsSens: 6,
        rawInput: true,
    },
    {
        slug: 'zywoo',
        name: 'ZywOo',
        realName: 'Mathieu Herbaut',
        game: 'CS2',
        gameId: 'csgo',
        team: 'Team Vitality',
        country: 'France',
        countryFlag: '🇫🇷',
        dpi: 400,
        sens: 2.0,
        cm360: cm360CS2(400, 2.0),
        edpi: 800,
        mouse: 'Pulsar Xlite V3',
        mouseSlug: 'pulsar-xlite-v3',
        keyboard: 'Wooting 60HE',
        headset: 'Sennheiser HD 560S',
        monitor: 'BenQ ZOWIE XL2546K',
        monitorHz: 240,
        mousepad: 'Artisan Zero FX L',
        role: 'AWPer',
        active: true,
        achievements: ['HLTV #1 Player 2019 & 2020', 'IEM Cologne 2022 Winner', 'BLAST Premier 2023'],
        social: { twitter: 'ZywOo', twitch: 'zywoo' },
        bio: 'ZywOo is the French prodigy who went straight from MM to the world stage. Named HLTV #1 twice before turning 20, his smooth 2.0 sensitivity at 400 DPI produces some of the most precise AWP shots ever recorded.',
        pollingRate: 1000,
        windowsSens: 6,
        rawInput: true,
    },
    {
        slug: 'm0nesy',
        name: 'm0NESY',
        realName: 'Ilya Osipov',
        game: 'CS2',
        gameId: 'csgo',
        team: 'G2 Esports',
        country: 'Russia',
        countryFlag: '🇷🇺',
        dpi: 400,
        sens: 2.3,
        cm360: cm360CS2(400, 2.3),
        edpi: 920,
        mouse: 'Logitech G Pro X Superlight 2',
        mouseSlug: 'logitech-g-pro-x-superlight-2',
        keyboard: 'Logitech G PRO X',
        headset: 'Logitech G PRO X 2',
        monitor: 'ASUS ROG Swift PG259QN',
        monitorHz: 360,
        mousepad: 'Logitech G640',
        role: 'AWPer / Entry',
        active: true,
        achievements: ['IEM Cologne 2023 Winner', 'HLTV Top 5 2023', 'G2 Ace AWPer'],
        social: { twitter: 'm0NESY' },
        bio: 'm0NESY is one of the most talented young players in CS2. His aggressive AWPing style combined with a 2.3 sensitivity allows for rapid angle checks and devastating one-taps.',
        pollingRate: 1000,
        windowsSens: 6,
        rawInput: true,
    },
    {
        slug: 'device',
        name: 'dev1ce',
        realName: 'Nicolai Reedtz',
        game: 'CS2',
        gameId: 'csgo',
        team: 'Astralis',
        country: 'Denmark',
        countryFlag: '🇩🇰',
        dpi: 400,
        sens: 1.9,
        cm360: cm360CS2(400, 1.9),
        edpi: 760,
        mouse: 'Astralis Fnatic ZOWIE SFK2-NE',
        mouseSlug: 'zowie-sfk2',
        keyboard: 'SteelSeries Apex Pro',
        headset: 'SteelSeries Arctis Pro',
        monitor: 'BenQ ZOWIE XL2546K',
        monitorHz: 240,
        mousepad: 'Zowie G-SR-SE',
        role: 'AWPer',
        active: true,
        achievements: ['4x Major Champion', 'HLTV #1 Player 2016 & 2018', 'Astralis Dynasty Member'],
        social: { twitter: 'dev1ce', twitch: 'dev1ce' },
        bio: 'dev1ce is the most decorated AWPer in CS history with 4 Major titles. His 1.9 sens is a sweet spot that allows both the methodical crosshair placement he is known for and the reactive AWP shots that define his career.',
        pollingRate: 1000,
        windowsSens: 6,
        rawInput: true,
    },
    {
        slug: 'ropz',
        name: 'ropz',
        realName: 'Robin Kool',
        game: 'CS2',
        gameId: 'csgo',
        team: 'FaZe Clan',
        country: 'Estonia',
        countryFlag: '🇪🇪',
        dpi: 400,
        sens: 1.09,
        cm360: cm360CS2(400, 1.09),
        edpi: 436,
        mouse: 'Logitech G Pro X Superlight 2',
        mouseSlug: 'logitech-g-pro-x-superlight-2',
        keyboard: 'Logitech G PRO X',
        headset: 'Logitech G PRO X 2',
        monitor: 'BenQ ZOWIE XL2546K',
        monitorHz: 240,
        mousepad: 'Artisan Zero FX L',
        role: 'Rifler',
        active: true,
        achievements: ['PGL Major Antwerp 2022 Winner', 'IEM Katowice 2022', 'HLTV Top 5 2022'],
        social: { twitter: 'ropz', twitch: 'ropz' },
        bio: 'ropz is one of the cleanest riflers in the world. His very low 1.09 sensitivity gives him extraordinary precision and consistency. He rose from anonymity on a Faceit ladder to become a FaZe Clan star.',
        pollingRate: 1000,
        windowsSens: 6,
        rawInput: true,
    },
    {
        slug: 'broky',
        name: 'broky',
        realName: 'Helvijs Saukants',
        game: 'CS2',
        gameId: 'csgo',
        team: 'FaZe Clan',
        country: 'Latvia',
        countryFlag: '🇱🇻',
        dpi: 400,
        sens: 1.55,
        cm360: cm360CS2(400, 1.55),
        edpi: 620,
        mouse: 'Logitech G Pro X Superlight',
        mouseSlug: 'logitech-g-pro-x-superlight',
        keyboard: 'HyperX Alloy Origins Core',
        headset: 'HyperX Cloud Alpha',
        monitor: 'BenQ ZOWIE XL2546K',
        monitorHz: 240,
        mousepad: 'Logitech G840',
        role: 'AWPer / Support',
        active: true,
        achievements: ['PGL Major Antwerp 2022 Winner', 'FaZe Core'],
        social: { twitter: 'brokyCS', twitch: 'broky' },
        bio: 'broky is FaZe Clan\'s primary AWPer, known for his calm, methodical approach. His 1.55 sensitivity sits comfortably in the mid-range for professional AWPers.',
        pollingRate: 1000,
        windowsSens: 6,
        rawInput: true,
    },
    {
        slug: 'karrigan',
        name: 'karrigan',
        realName: 'Finn Andersen',
        game: 'CS2',
        gameId: 'csgo',
        team: 'FaZe Clan',
        country: 'Denmark',
        countryFlag: '🇩🇰',
        dpi: 400,
        sens: 2.2,
        cm360: cm360CS2(400, 2.2),
        edpi: 880,
        mouse: 'Logitech G Pro X Superlight 2',
        mouseSlug: 'logitech-g-pro-x-superlight-2',
        keyboard: 'Razer BlackWidow',
        headset: 'HyperX Cloud Alpha',
        monitor: 'BenQ ZOWIE XL2546K',
        monitorHz: 240,
        mousepad: 'Logitech G840',
        role: 'IGL',
        active: true,
        achievements: ['PGL Major Antwerp 2022 Winner', 'ESL One Cologne 2016', 'Longest IGL Career in CS'],
        social: { twitter: 'karrigaN', twitch: 'karrigan' },
        bio: 'karrigan is the legendary IGL of FaZe Clan, credited with masterminding one of the most dominant team runs in CS history. His higher 2.2 sensitivity reflects his role as an entry-oriented IGL.',
        pollingRate: 1000,
        windowsSens: 6,
        rawInput: true,
    },
    {
        slug: 'electronic',
        name: 'electronic',
        realName: 'Denis Sharipov',
        game: 'CS2',
        gameId: 'csgo',
        team: 'NAVI',
        country: 'Russia',
        countryFlag: '🇷🇺',
        dpi: 400,
        sens: 1.75,
        cm360: cm360CS2(400, 1.75),
        edpi: 700,
        mouse: 'Logitech G Pro X Superlight 2',
        mouseSlug: 'logitech-g-pro-x-superlight-2',
        keyboard: 'Logitech G PRO X',
        headset: 'Logitech G PRO X',
        monitor: 'BenQ ZOWIE XL2546K',
        monitorHz: 240,
        mousepad: 'HyperX Fury S Pro',
        role: 'Rifler',
        active: true,
        achievements: ['PGL Major Stockholm 2021', 'NAVI HLTV Top 10 2021'],
        social: { twitter: 'electronicCSGO' },
        bio: 'electronic is a rifling powerhouse and the backbone of NAVI\'s fragging. His 1.75 sensitivity provides excellent balance between fast flicks and precise tracking.',
        pollingRate: 1000,
        windowsSens: 6,
        rawInput: true,
    },

    // ─── APEX LEGENDS ────────────────────────────────────────────────────────
    {
        slug: 'imperialhal',
        name: 'ImperialHal',
        realName: 'Philip Dosen',
        game: 'Apex Legends',
        gameId: 'apex',
        team: 'TSM',
        country: 'United States',
        countryFlag: '🇺🇸',
        dpi: 400,
        sens: 2.0,
        cm360: cm360Apex(400, 2.0),
        edpi: 800,
        mouse: 'Logitech G Pro X Superlight 2',
        mouseSlug: 'logitech-g-pro-x-superlight-2',
        keyboard: 'Logitech G PRO X',
        headset: 'Sennheiser GSX 1000',
        monitor: 'BenQ ZOWIE XL2546K',
        monitorHz: 240,
        mousepad: 'Logitech G640',
        role: 'IGL / Fraggers',
        active: true,
        achievements: ['ALGS Year 3 Champion', 'TSM Apex Captain', 'Most Popular Apex Streamer'],
        social: { twitter: 'TSM_ImperialHal', twitch: 'imperialhal' },
        bio: 'ImperialHal is the face of competitive Apex Legends. As the IGL and best player of TSM, his in-game callouts and mechanical skill have led his team to multiple ALGS championships.',
        pollingRate: 1000,
        windowsSens: 6,
        rawInput: true,
    },
    {
        slug: 'sweetdreams',
        name: 'SweetDreams',
        realName: 'Conner Doyle',
        game: 'Apex Legends',
        gameId: 'apex',
        team: 'Sentinels',
        country: 'Canada',
        countryFlag: '🇨🇦',
        dpi: 800,
        sens: 1.2,
        cm360: cm360Apex(800, 1.2),
        edpi: 960,
        mouse: 'Logitech G Pro X Superlight 2',
        mouseSlug: 'logitech-g-pro-x-superlight-2',
        keyboard: 'Logitech G PRO X',
        headset: 'Logitech G PRO X 2',
        monitor: 'Alienware AW2521H',
        monitorHz: 360,
        mousepad: 'Logitech G640',
        role: 'Support / IGL',
        active: true,
        achievements: ['ALGS Split 2 Playoffs 2023', 'Sentinels Apex IGL'],
        social: { twitter: 'SentinelsSweetDreams', twitch: 'sweetdreams' },
        bio: 'SweetDreams is one of the most consistent competitors in Apex Legends. His leadership and game sense make him the strategic anchor of the Sentinels roster.',
        pollingRate: 1000,
        windowsSens: 6,
        rawInput: true,
    },

    // ─── OVERWATCH 2 ──────────────────────────────────────────────────────────
    {
        slug: 'someone',
        name: 'Someone',
        realName: 'Sumin Park',
        game: 'Overwatch 2',
        gameId: 'overwatch',
        team: 'Seoul Dynasty',
        country: 'South Korea',
        countryFlag: '🇰🇷',
        dpi: 800,
        sens: 5.5,
        cm360: cm360OW2(800, 5.5),
        edpi: 4400,
        mouse: 'Logitech G Pro X Superlight 2',
        mouseSlug: 'logitech-g-pro-x-superlight-2',
        keyboard: 'Logitech G PRO X',
        headset: 'Logitech G PRO X',
        monitor: 'BenQ ZOWIE XL2546K',
        monitorHz: 240,
        mousepad: 'Logitech G640',
        role: 'DPS',
        active: true,
        achievements: ['OWL 2022 Stage 3 MVP', 'Seoul Dynasty Star'],
        social: { twitter: 'OWL_Someone' },
        bio: 'Someone is one of Seoul Dynasty\'s premier DPS players. In Overwatch 2, where game sensitivity scales differently, his settings produce a competitive cm/360 that suits the game\'s faster movement mechanics.',
        pollingRate: 1000,
        windowsSens: 6,
        rawInput: true,
    },

    // ─── FORTNITE ─────────────────────────────────────────────────────────────
    {
        slug: 'bugha',
        name: 'Bugha',
        realName: 'Kyle Giersdorf',
        game: 'Fortnite',
        gameId: 'fortnite',
        team: 'Sentinels',
        country: 'United States',
        countryFlag: '🇺🇸',
        dpi: 400,
        sens: 0.08,
        cm360: parseFloat(((360 / (0.08 * 0.005555 * 400)) * 2.54).toFixed(2)),
        edpi: 32,
        mouse: 'Logitech G Pro X Superlight 2',
        mouseSlug: 'logitech-g-pro-x-superlight-2',
        keyboard: 'Logitech G PRO X',
        headset: 'SteelSeries Arctis Pro',
        monitor: 'Alienware AW2521H',
        monitorHz: 360,
        mousepad: 'Logitech G640',
        role: 'Solo',
        active: true,
        achievements: ['Fortnite World Cup Solo Winner 2019', '$3M Prize Winner'],
        social: { twitter: 'bugha', twitch: 'bugha' },
        bio: 'Bugha became a global sensation when he won the Fortnite World Cup Solo at just 16 years old, taking home $3 million. His extremely low X sensitivity (0.08) gives him exceptional building precision.',
        pollingRate: 1000,
        windowsSens: 6,
        rawInput: true,
    },
];

// Helper to get a pro by slug
export function getProBySlug(slug: string): ProPlayer | undefined {
    return pros.find(p => p.slug === slug);
}

// Helper to get pros by game
export function getProsByGame(gameId: string): ProPlayer[] {
    return pros.filter(p => p.gameId === gameId);
}

// Get all unique games
export function getProGames(): string[] {
    return [...new Set(pros.map(p => p.game))];
}

// Get all slugs (for generateStaticParams)
export function getProSlugs(): string[] {
    return pros.map(p => p.slug);
}
